apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: portfolio-website
        image: docker.io/sovu/portfolio-website:latest
        ports:
        - containerPort: 80
